# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'POM.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 576))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 576))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./data/tmp4design/负面舆情帽子蓝.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTip("")
        MainWindow.setStatusTip("")
        MainWindow.setWhatsThis("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.zhihu_img = QtWidgets.QLabel(self.centralwidget)
        self.zhihu_img.setGeometry(QtCore.QRect(210, 70, 371, 161))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zhihu_img.sizePolicy().hasHeightForWidth())
        self.zhihu_img.setSizePolicy(sizePolicy)
        self.zhihu_img.setStyleSheet("image: url(./data/tmp4design/知乎知乎蓝色.png);")
        self.zhihu_img.setText("")
        self.zhihu_img.setObjectName("zhihu_img")
        self.title_img = QtWidgets.QLabel(self.centralwidget)
        self.title_img.setGeometry(QtCore.QRect(190, 220, 211, 71))
        self.title_img.setStyleSheet("image: url(./data/tmp4design/话题精华分析.png);")
        self.title_img.setText("")
        self.title_img.setObjectName("title_img")
        self.img_change0 = QtWidgets.QLabel(self.centralwidget)
        self.img_change0.setGeometry(QtCore.QRect(520, 50, 381, 311))
        self.img_change0.setStyleSheet("image: url(./data/tmp4design/舆情监控蓝500.png);")
        self.img_change0.setText("")
        self.img_change0.setObjectName("img_change0")
        self.info = QtWidgets.QTextBrowser(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(260, 420, 541, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info.sizePolicy().hasHeightForWidth())
        self.info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.info.setFont(font)
        self.info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.info.setLineWidth(1)
        self.info.setObjectName("info")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 530, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(6)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.analysis_btn = QtWidgets.QPushButton(self.centralwidget)
        self.analysis_btn.setGeometry(QtCore.QRect(530, 330, 100, 38))
        self.analysis_btn.setObjectName("analysis_btn")
        self.query_btn = QtWidgets.QPushButton(self.centralwidget)
        self.query_btn.setGeometry(QtCore.QRect(790, 360, 100, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_btn.sizePolicy().hasHeightForWidth())
        self.query_btn.setSizePolicy(sizePolicy)
        self.query_btn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.query_btn.setObjectName("query_btn")
        self.key_words_le = QtWidgets.QLineEdit(self.centralwidget)
        self.key_words_le.setGeometry(QtCore.QRect(170, 300, 201, 31))
        self.key_words_le.setInputMask("")
        self.key_words_le.setText("")
        self.key_words_le.setMaxLength(32767)
        self.key_words_le.setObjectName("key_words_le")
        self.start_time_le = QtWidgets.QLineEdit(self.centralwidget)
        self.start_time_le.setGeometry(QtCore.QRect(170, 350, 111, 31))
        self.start_time_le.setObjectName("start_time_le")
        self.end_time_le = QtWidgets.QLineEdit(self.centralwidget)
        self.end_time_le.setGeometry(QtCore.QRect(320, 350, 111, 31))
        self.end_time_le.setObjectName("end_time_le")
        self.class_num = QtWidgets.QLineEdit(self.centralwidget)
        self.class_num.setGeometry(QtCore.QRect(390, 300, 41, 31))
        self.class_num.setObjectName("class_num")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(640, 340, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "个人知乎话题精华舆情系统"))
        self.zhihu_img.setToolTip(_translate("MainWindow", "<html><head/><body><p>多点两下？或许有惊喜？</p></body></html>"))
        self.info.setToolTip(_translate("MainWindow", "<html><head/><body><p>这里是交互提示窗口</p></body></html>"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>本程序只为毕业设计和学习使用，如有侵权，联系本人删除 851688393@qq.com</p></body></html>"))
        self.label.setText(_translate("MainWindow", "Copyright © 2020 sunglitau, All things for study."))
        self.analysis_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>点击按钮，将开始分析相关信息</p></body></html>"))
        self.analysis_btn.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.analysis_btn.setText(_translate("MainWindow", "分析"))
        self.query_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>点击按钮，将进行数据获取操作并且获得文摘并追加情感值</p></body></html>"))
        self.query_btn.setText(_translate("MainWindow", "查询"))
        self.key_words_le.setToolTip(_translate("MainWindow", "<html><head/><body><p>依赖知乎的搜索引擎，请确认关键字话题是否存在</p></body></html>"))
        self.start_time_le.setToolTip(_translate("MainWindow", "<html><head/><body><p>请输入8位日期如20200202； 实时模式下请最好填入这个起始值</p></body></html>"))
        self.end_time_le.setToolTip(_translate("MainWindow", "<html><head/><body><p>请输入8位日期; 实时模式下这个值无效（默认今天）</p></body></html>"))
        self.class_num.setToolTip(_translate("MainWindow", "<html><head/><body><p>您想分成几类呢？</p></body></html>"))
        self.checkBox.setToolTip(_translate("MainWindow", "勾选该按钮后，开始分析时会自动在指定周期内发送文件到指定邮箱"))
        self.checkBox.setText(_translate("MainWindow", "实时模式"))
# import pom_rc
